'use client';

import React, { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
import { fetchInvoices } from '@/redux/features/invoiceSlice';
import Link from 'next/link';
import Loader from '@/components/Loader';
import ReportActions from '@/components/ReportActions';
import Breadcrumb from '@/components/Breadcrumb';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const InvoiceReportPage = () => {
  const [mounted, setMounted] = useState(false);
  const [search, setSearch] = useState('');
  const dispatch = useDispatch();
  const { company: activeCompany } = useSelector((state: RootState) => state.auth);
  const { items: invoices, loading } = useSelector((state: RootState) => state.invoices);

  useEffect(() => {
    setMounted(true);
    if (activeCompany?.id) {
      (dispatch as any)(fetchInvoices(activeCompany.id));
    }
  }, [dispatch, activeCompany?.id]);

  if (!mounted) return null;

  const filteredInvoices = invoices.filter(inv => {
    const searchTerm = search.toLowerCase();
    return (
      (inv.customerName?.toLowerCase() ?? '').includes(searchTerm) ||
      (inv.invoiceNumber?.toLowerCase() ?? '').includes(searchTerm)
    );
  });

  const handlePrintRecord = (inv: any) => {
    const printWindow = window.open('', '', 'height=600,width=800');
    if (!printWindow) return;
    printWindow.document.write('<html><head><title>Invoice Summary</title>');
    printWindow.document.write('<style>body { font-family: sans-serif; padding: 40px; color: #333; } .header { border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; } .label { font-weight: bold; color: #666; font-size: 0.8rem; text-transform: uppercase; margin-bottom: 4px; } .value { font-size: 1.1rem; margin-bottom: 20px; font-weight: 500; } .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }</style>');
    printWindow.document.write('</head><body>');
    printWindow.document.write('<div class="header"><h1 style="margin: 0; color: #2563eb;">Globus Engineering</h1><p style="margin: 5px 0 0; color: #666;">Invoice Summary Statement</p></div>');
    printWindow.document.write('<div class="grid">');
    printWindow.document.write(`<div><div class="label">Customer</div><div class="value">${inv.customerName}</div></div>`);
    printWindow.document.write(`<div><div class="label">Invoice No</div><div class="value">${inv.invoiceNumber}</div></div>`);
    printWindow.document.write(`<div><div class="label">Date</div><div class="value">${inv.date}</div></div>`);
    printWindow.document.write(`<div><div class="label">Grand Total</div><div class="value">INR ${inv.grandTotal.toLocaleString()}</div></div>`);
    printWindow.document.write('</div>');
    printWindow.document.write('<div style="margin-top: 50px; text-align: center; font-size: 0.8rem; color: #999; border-top: 1px solid #eee; padding-top: 20px;">Generated by Globus System on ' + new Date().toLocaleString() + '</div>');
    printWindow.document.write('</body></html>');
    printWindow.document.close();
    printWindow.print();
  };

  const handleExportPDFRecord = (inv: any) => {
    const doc = new jsPDF();
    doc.setFillColor(37, 99, 235); doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255); doc.setFontSize(22); doc.text("GLOBUS ENGINEERING", 14, 25);
    doc.setFontSize(10); doc.text("INVOICE SUMMARY RECORD", 14, 32);
    doc.setTextColor(33, 33, 33);
    autoTable(doc, {
      startY: 55,
      body: [
        ['Customer', inv.customerName], ['Invoice Number', inv.invoiceNumber],
        ['Billing Date', inv.date], ['Grand Total', `INR ${inv.grandTotal.toLocaleString()}`]
      ],
      theme: 'grid', styles: { cellPadding: 8, fontSize: 10 },
      columnStyles: { 0: { fontStyle: 'bold', fillColor: [245, 245, 245], cellWidth: 50 } },
    });
    doc.save(`invoice_${inv.invoiceNumber}.pdf`);
  };

  return (
    <div className="container-fluid py-4 animate-fade-in bg-light min-vh-100">
      <div className="d-flex justify-content-between align-items-center mb-4 px-2">
        <div>
          <Breadcrumb items={[{ label: 'Intelligence Reports', active: false }, { label: 'Invoice Report', active: true }]} />
          <h2 className="fw-900 mb-1 text-dark tracking-tight mt-2">Invoice Report</h2>
          <p className="text-muted small mb-0 font-weight-500">Comprehensive summary of all generated invoices and billing statements.</p>
        </div>
        <button className="btn btn-white shadow-sm border border-light px-3 d-flex align-items-center gap-2" onClick={() => (dispatch as any)(fetchInvoices(activeCompany?.id))}>
          <i className="bi bi-arrow-repeat text-primary fw-bold"></i>
          <span className="small fw-800 text-muted">REFRESH</span>
        </button>
      </div>

      <div className="card border-0 shadow-sm mb-4 overflow-hidden rounded-4">
        <div className="card-body p-3">
          <div className="row g-3 align-items-center">
            <div className="col-lg-5 col-md-4">
              <div className="position-relative">
                <i className="bi bi-search position-absolute top-50 start-0 translate-middle-y ms-3 text-muted"></i>
                <input type="text" className="form-control ps-5 border-0 bg-light-soft" placeholder="Search customer or invoice..." value={search} onChange={(e) => setSearch(e.target.value)} style={{ height: '42px', borderRadius: '10px' }} />
              </div>
            </div>
            <div className="col-lg-2 col-md-3">
              <select className="form-select border-0 bg-light-soft" style={{ height: '42px', borderRadius: '10px' }}>
                <option>All Transactions</option>
              </select>
            </div>
            <div className="col-auto ms-auto d-flex justify-content-end">
              <ReportActions />
            </div>
          </div>
        </div>
      </div>

      <div className="card border-0 shadow-sm overflow-hidden rounded-4">
        <div className="card-body p-0">
          <div className="table-responsive" style={{ minHeight: '400px', paddingBottom: '80px' }}>
            <table className="table table-hover align-middle mb-0">
              <thead className="bg-light">
                <tr className="text-uppercase small fw-bold text-muted">
                  <th className="px-4 py-3 border-0">Sno</th>
                  <th className="py-3 border-0">Date</th>
                  <th className="py-3 border-0">Invoice No</th>
                  <th className="py-3 border-0">Customer Name</th>
                  <th className="py-3 border-0 text-end">Subtotal</th>
                  <th className="py-3 border-0 text-end">Taxes</th>
                  <th className="py-3 border-0 text-end">Grand Total</th>
                  <th className="py-3 border-0 text-center px-4" style={{ width: '120px' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr><td colSpan={8}><Loader text="Compiling Data..." /></td></tr>
                ) : filteredInvoices.map((inv, index) => (
                  <tr key={inv.id} className="border-bottom border-light">
                    <td className="px-4 small text-muted font-monospace">{index + 1}</td>
                    <td className="small text-muted">{inv.date}</td>
                    <td className="text-dark fw-bold">{inv.invoiceNumber}</td>
                    <td className="text-dark fw-800 text-uppercase" style={{ fontSize: '0.85rem' }}>{inv.customerName}</td>
                    <td className="text-end small">₹{inv.subTotal?.toLocaleString()}</td>
                    <td className="text-end small text-muted">₹{inv.taxTotal?.toLocaleString()}</td>
                    <td className="text-end fw-900 text-dark px-2">₹{inv.grandTotal?.toLocaleString()}</td>
                    <td className="text-center px-4">
                      <div className="d-flex justify-content-center align-items-center gap-1">
                        <Link href={`/invoices/${inv.id}`} className="btn-action-view" title="View Detail"><i className="bi bi-eye-fill"></i></Link>
                        <div className="dropdown">
                          <button className="btn btn-sm btn-outline-secondary border-0 text-muted p-0 ms-1 d-flex align-items-center justify-content-center" type="button" id={`actions-${inv.id}`} data-bs-toggle="dropdown" aria-expanded="false" style={{ width: '32px', height: '32px', borderRadius: '8px' }}>
                            <i className="bi bi-three-dots-vertical fs-5"></i>
                          </button>
                          <ul className="dropdown-menu dropdown-menu-end shadow-sm border-0 rounded-3 py-2" aria-labelledby={`actions-${inv.id}`}>
                            <li><button className="dropdown-item d-flex align-items-center gap-2 py-2" type="button" onClick={() => handlePrintRecord(inv)}><i className="bi bi-printer text-primary"></i> <span className="small fw-semibold">Quick Print</span></button></li>
                            <li><button className="dropdown-item d-flex align-items-center gap-2 py-2" type="button" onClick={() => handleExportPDFRecord(inv)}><i className="bi bi-file-earmark-pdf text-danger"></i> <span className="small fw-semibold">Export PDF</span></button></li>
                          </ul>
                        </div>
                      </div>
                    </td>
                  </tr>
                ))
                }
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <style jsx>{` .fw-900 { font-weight: 900; } .bg-light-soft { background-color: #f7f9fc; } .table-responsive { padding-bottom: 80px; } `}</style>
    </div>
  );
};

export default InvoiceReportPage;
